### PR TITLE
Update 1.11 release notes

### PR DESCRIPTION
**Pull request by mathstuf**
---
This change came as news to us. Adding a release note and compatibility for others in the future :) .

### CODE REVIEW

**Comment by zeux** [comment]
This definitely wasn't intended. CMakeLists.txt does have this:

```
add_library(pugixml INTERFACE)
target_link_libraries(pugixml INTERFACE ${pugixml-alias})
add_library(pugixml::pugixml ALIAS pugixml)
```

So I'd think that pugixml::pugixml and pugixml are already equivalent - is that not the case?

**Comment by zeux** [comment]
(and your change would make the alias self-recursive which doesn't seem right, but I'm not a CMake expert so maybe I'm missing something)

**Comment by mathstuf** [comment]
My change is for users of `find_package(pugixml)` which work with 1.10 so that they continue to work with 1.12 and newer (1.11 being the "broken" release without compat).

**Comment by zeux** [comment]
Mhm - before the CMake rework I can see this worked as is after using find_package:

> target_link_libraries(test pugixml)

But after it doing this doesn't seem to add public includes so `#include "pugixml.hpp"` doesn't work. Using `pugixml::pugixml` target fixes this.

I'd rather fix this unconditionally because the intention was to make it possible to depend on `pugixml` throughout the transition but I'm not sure what the best option to do so is - a circular alias seems wrong to me. @slurps-mad-rips any comments?

**Comment by zeux** [comment]
Full example that I've tried:

test.cpp:
```
#include "pugixml.hpp"

int main()
{
    pugi::xml_document doc;
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.0)
project(test)
add_executable(test test.cpp)
find_package(pugixml)
target_link_libraries(test pugixml)
```

**Comment by mathstuf** [comment]
> I'd rather fix this unconditionally because the intention was to make it possible to depend on pugixml throughout the transition but I'm not sure what the best option to do so is - a circular alias seems wrong to me.

There is no circular alias. the `add_library(pugixml::pugixml ALIAS)` call in `CMakeLists.txt` makes `pugixml::pugixml` work in the pugixml build. The one I'm adding here makes `pugixml` available at `find_package(pugixml)` time (currently, no such target exists).

**Comment by zeux** [comment]
Ahh the change is in the .cmake.in file - I missed that. Would there be any harm in adding this alias unconditionally?

**Comment by mathstuf** [comment]
I think it'd be nice to deprecate the old, un-namespaced, target eventually. The way it is now in this PR is that `find_package(pugixml 1.11)` would *not* provide the old target, but `find_package(pugixml 1.9)` *would* provide it (so that there's only one target name to use).

**Comment by zeux** [comment]
I guess I don't see the potential for the deprecation until 2.0... But this doesn't seem to be harmful so I'll merge this as is. Thanks!

**Comment by randyfan** [comment]
I'm getting the following error: 
image

Here's a screenshot of my CMakeLists.txt which uses find_package(pugixml REQUIRED):
image

Any ideas what's causing the configure error?

**Comment by mathstuf** [comment]
Fixed in #389.

**Pull request merged**
