### PR TITLE
Various CMake improvements

### PR DESCRIPTION
**Pull request by KyleFromKitware**
Fixes: #344

### CODE REVIEW

**Comment by KyleFromKitware** [comment]
Cc: @bradking @chuckatkins @eisenhauer @slurps-mad-rips

**Comment by zeux** [comment]
This looks good to me! Will keep this open for a day or two to let others comment since I'm not a CMake expert. From the looks of this this also fixes #344, is that right?

**Comment by KyleFromKitware** [comment]
> From the looks of this this also fixes #344, is that right?

Indeed it does. I will update the description accordingly.

**Comment by KyleFromKitware** [comment]
> Will keep this open for a day or two to let others comment since I'm not a CMake expert.

I am CMake upstream, so I am a CMake expert :) I would very much like to get @slurps-mad-rips' feedback, since they originally wrote this code.

**Comment by sethrj** [comment]
Thank you @KyleFromKitware ! I hit two separate cmake errors on the latest tagged build of pugixml that this PR fixes -- the duplicate library names and the lack of a namespaced target name.

@zeux is there any chance of adding a "patch" (v0.10.1) release soon for this and other recent fixes? Thanks!

**Comment by zeux** [comment]
I can release 0.11, looks like it’s been a year since last release (tine flies!). Will probably happen by the end of the month, need to triage open issues/PRs.

**Comment by zeux** [comment]
#383

**Pull request merged**
