### PR TITLE
Remove static pivot from NuGet autopkg.

### PR DESCRIPTION
**Pull request by steji113**
This pivot seemed to be causing issues because the NuGet package thought it was actually dynamic.

Refs #107

### CODE REVIEW

**Comment by zeux** [comment]
Hmm - this is strange.

According to http://coapp.org/reference/autopackage-ref.html, static = static library; not sure what the default is but if it's dynamic, it'd try to link pugixml as DLL which it's not?

Can you clarify on what issue you're currently seeing if you keep static? The original NuGet package used static for VS2015 and it worked fine there.

**Comment by zeux** [comment]
I guess maybe it does not matter since the linker will correctly link in the static library regardless of what NuGet thinks, and since we only really have one option for this pivot it is probably reduntant.

**Comment by steji113** [comment]
In the pugixml.targets file that is automatically generated it sets the linkage to dynamic, but then the conditions for linking were looking for it to be set to static. The documentation from CoApp.com is quite poor in this area :(

**Comment by steji113** [comment]
BTW, I put this generated package in my solution and it seemed to fix the issue!

**Comment by zeux** [comment]
I've uploaded pugixml 1.7.2 to nuget with this fix

**Comment by steji113** [comment]
@zeux Thank you for all of your assistance on this. It worked beautifully on VS 2013 Win32 - Release / Debug and x64 - Release / Debug.

**Comment by zeux** [comment]
Verified it works for VS2015 as well, so the Appveyor build is working well which is great. I'll keep the nuget-1.7 branch around for now in case I need to add any more VS versions/configurations. Thanks for the pull requests!

**Comment by steji113** [comment]
Absolutely!

**Pull request merged**
