### PR TITLE
format_skip_control_chars

### LINKED ISSUE #262: Form feed character is encoded as &#12; which is invalid xml 1.0
`\f` character after decoding xml tree to string becomes `&#12;`. Well, any character within range [1; 31] except some valid ones (`\t \n \r`) is encoded this way.

### PR DESCRIPTION
**Pull request by Yanpas**
Fixes #262

### CODE REVIEW

**Comment by zeux** [comment]
Thanks, the change itself looks good. It would be great to add a simple unit tests and add this flag to manual (docs/manual.adoc) - you can find any other format flag in tests/docs for guidance. No need to rebuild HTML documentation, the setup process for that is nontrivial if you’re on Windows...

**Comment by Yanpas** [comment]
Done. By the way debugging unittest was tricky since it only printed expected string, but not the actual result.

And about 18 unit tests were failing on Linux gcc 8.2.0... I'll take a look while be near my linux machine, maybe the cause was I was running them from wrong directory.

**Comment by zeux** [comment]
`make test` should run them from the correct folder

**Comment by zeux** [comment]
Merged, thanks!

**Pull request merged**
