### PR TITLE
add cocoapods package

### PR DESCRIPTION
**Pull request by igagis**
This is the PR to fix https://github.com/zeux/pugixml/issues/84

### CODE REVIEW

**Comment by zeux** [comment]
My understanding is that LICENSE file is not used - is this accurate?

It's a bit of a shame that the license exists in a lot of copies, but since it already does and you have to embed it in the spec file as well, might as well not have a LICENSE file...

**Comment by igagis** [comment]
When pushing podspec to cocoapods repo it validates the podspec and sources, and during that it checks if there is a license, If there  is a LICENSE file it is ok. Other approach is to embed the license right into the podspec, then it will also pass the validation even without LICENSE file.

It is preferred to have LICENSE file and not have the license embedded in podspec. The only reason  I embedded it is that for now I used 1.7 tag to package sources for cocoapods (podspec refers to 1.7 git tag) and 1.7 tag does not have the LICENSE file.

So, the embedded license should be removed from podspec when LICENSE file is merged to master and a new version tag is created.

**Comment by zeux** [comment]
Ok. I don't see much of a point of having another place to put the license in at the top level since it's already in two readme files and in every source file. IMO if a package manager requires a license and allows embedding it into a configuration file that's perfect.

Thanks for the PR!

**Comment by igagis** [comment]
For the same reason, I prefer to have one LICENSE file and no license in every source file or any other places. But no problem, if it is more convenient for you :).

Your're welcome!

**Comment by zeux** [comment]
Yeah, I'd very much prefer just once license boilerplate but unfortunately people have asked me before to add it verbatim to sources so that when they embed the sources in their codebase it's obvious that it's legal, it has to be in documentation and I'm not sure if documentation formats I'm using support file includes, it has to be there in the README.md since people want to know, etc. etc. :)

**Pull request merged**
