### PR TITLE
Add LICENSE.md to RELEASE

### PR DESCRIPTION
**Pull request by c72578**

### CODE REVIEW

**Comment by zeux** [comment]
These files seem redundant wrt readme.txt that's already included in the archive (which is why they were left out) - can you clarify why they are necessary?

**Comment by c72578** [comment]
The file LICENSE.md looks like the obvious "license file" of pugixml. "License files" are frequently packaged together with the source. Furthermore, the file LICENSE.md is referenced from README.md:

> This library is available to anybody free of charge, under the terms of MIT License (see LICENSE.md).

So I guess it would make sense to distribute both, LICENSE.md for the license file and README.md for some initial reading/information.

**Comment by zeux** [comment]
But readme.txt already includes initial reading  information as well as the full license text (and license boilerplate is also duplicated in headers/sources).

I guess my point is that not including this into the release archive is not an oversight, it’s a conscious choice to minimize the amount  of redundancy (which readme do you open? If readme.txt is omitted, what do novice users do with the fact that .md doesn’t have a default Windows file association? etc).

So including this requires that to solve some problem that’s more important than having two readme files in the archive.

**Comment by hobbes1069** [comment]
From a packaging point of view it’s preferable to have the README and LICENSE separate. For low space devices (arm) the license file is installed by necessity but other documentation is not.

**Comment by zeux** [comment]
I am probably missing some context here. If having a license file be separate from readme is a packaging requirement I am up for including LICENSE.md into the release archives but it doesn’t seem like this necessitates inclusion of README.md.

**Comment by c72578** [comment]
OK, I have updated the PR now, so that only LICENSE.md is added to RELEASE.

**Comment by hobbes1069** [comment]
It's not a hard requirement but is typical. Pretty much all of the 150 packages I maintain for Fedora have a LICENSE or COPYING file. It gets marked as a license file in the RPM spec file while the rest get marked as documentation.

**Comment by zeux** [comment]
Thanks!

**Pull request merged**
