### PR TITLE
Add support for Visual Studio 2022 with Platform Toolset v143.

### PR DESCRIPTION
**Pull request by appls**
Hi Arseny,
I would like to use pugixml within a project developed in VS 2022 with platform toolset v143. Please have a look at my pull request and if it is working as expected I am happy when you accept it and update the official Nuget package sources.
Cheers Tobias

### CODE REVIEW

**Comment by KrisWragg** [comment]
Would be nice to get an updated nuget package with this in as its currently blocking us updating some projects to VS2022 / VC143 unless we switch to headers only.

Looks like the VS2015 build failure was possibly an intermittent build issue?

```
Error uploading artifact to the storage: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
```

**Comment by appls** [comment]
Hi Kris,

I totally agree with you. My commits should not have any impact on the VS2015 build.
I am also looking forward to get an official package update, since we cannot update our productive systems where the build chain relies on the Nuget package system.
To me it seems that the maintainer, Arseny, is currently busy with other topics and we just have to stay patient.

@zeux Please let me know you need any further support.

Cheers
Tobias

**Comment by zeux** [comment]
I wasn't paying attention to this since the build looked as if it was broken, but after all the fixes it does look like VS2015 failure was spurious.

**Comment by zeux** [comment]
Thanks! I'll look into closing a couple other issues and making 1.12 release with updated NuGet packages

**Pull request merged**
