### PR TITLE
Update nuget creation to VS2019

### PR DESCRIPTION
**Pull request by Joelgranados**
Create visual studio projects that are vs2019 compliant.
* nuget_build.ps1 : Add two lines to the script that create builds for
v142 build tools

* pugixml_vs2019{,_static}.vcxproj :
Add two visual studio projects that build pugi with the latest SDK and
build tools

### CODE REVIEW

**Comment by c72578** [comment]
Please have a look also at this file:
appveyor.yml

**Comment by Joelgranados** [comment]
@c72578 I have updated the PR so it plays nicely with the appveyor workflow. It now creates a nuget package at the end that is usable in VS2019.

I did hit an issue when I tried to use VS2017 in the VS2019 build. It could not find the SDK needed from VS2017. The way I fixed this issue was to use VS2019 libs on v142, v141 and v140 parts of the nuget package. Is there another way around this issue in appveyor?

@c72578 @zeux : PR review greatly appreciated.

**Comment by zeux** [comment]
The issue is that if nuget package is built on multiple different AppVeyor agents, you'll end up with multiple NuGet packages. I'm not sure if there's a way to merge them. In the previous setup there was *one* agent (VS2017 image) that could build a package with all supported VS versions (2017, 2015, 2013). This meant that after building on AppVeyor I could grab the artifact file and just upload it to the package repository.

I don't fully understand the problem with the SDK setup. Is the issue that AppVeoyor 2019 image doesn't have a functioning VS2017?

**Comment by Joelgranados** [comment]
> The issue is that if nuget package is built on multiple different AppVeyor agents, you'll end up with multiple NuGet packages.
-> Yep. This is what I tried to avoid, but did not find a way to do it with the VS2019 agent.

> In the previous setup there was _one_ agent (VS2017 image) that could build a package with all supported VS versions (2017, 2015, 2013). This meant that after building on AppVeyor I could grab the artifact file and just upload it to the package repository.
-> And this is maintained if you try to build for VS2017, but hit the error and tired to re-adjust it for 2019.

> I don't fully understand the problem with the SDK setup. Is the issue that AppVeoyor 2019 image doesn't have a functioning VS2017?
-> This is what I get in AppVeyor if I just use VS2019:
`Build started
git clone -q --branch=update_to_vs2019 https://github.com/Joelgranados/pugixml.git C:\projects\pugixml
git checkout -qf a5e3a43b75edae2efde0c63098c547738c0ce567
if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019") { .\scripts\nuget_build.ps1 2019}
../src/pugiconfig.hpp -> nuget/build/native/include/pugiconfig.hpp
../src/pugixml.hpp -> nuget/build/native/include/pugixml.hpp
  pugixml.cpp
  pugixml_vs2019.vcxproj -> C:\projects\pugixml\scripts\vs2019\Win32_Debug\pugixml.lib
  pugixml.cpp
  pugixml_vs2019.vcxproj -> C:\projects\pugixml\scripts\vs2019\x64_Debug\pugixml.lib
vs2019/Win32_Debug/pugixml.lib -> nuget/build/native/lib/Win32/v142/dynamic/Debug/pugixml.lib
vs2019/x64_Debug/pugixml.lib -> nuget/build/native/lib/x64/v142/dynamic/Debug/pugixml.lib
  pugixml.cpp
  pugixml_vs2019.vcxproj -> C:\projects\pugixml\scripts\vs2019\Win32_Release\pugixml.lib
  pugixml.cpp
  pugixml_vs2019.vcxproj -> C:\projects\pugixml\scripts\vs2019\x64_Release\pugixml.lib
vs2019/Win32_Release/pugixml.lib -> nuget/build/native/lib/Win32/v142/dynamic/Release/pugixml.lib
vs2019/x64_Release/pugixml.lib -> nuget/build/native/lib/x64/v142/dynamic/Release/pugixml.lib
  pugixml.cpp
  pugixml_vs2019_static.vcxproj -> C:\projects\pugixml\scripts\vs2019\Win32_DebugStatic\pugixml.lib
  pugixml.cpp
  pugixml_vs2019_static.vcxproj -> C:\projects\pugixml\scripts\vs2019\x64_DebugStatic\pugixml.lib
vs2019/Win32_DebugStatic/pugixml.lib -> nuget/build/native/lib/Win32/v142/static/Debug/pugixml.lib
vs2019/x64_DebugStatic/pugixml.lib -> nuget/build/native/lib/x64/v142/static/Debug/pugixml.lib
  pugixml.cpp
  pugixml_vs2019_static.vcxproj -> C:\projects\pugixml\scripts\vs2019\Win32_ReleaseStatic\pugixml.lib
  pugixml.cpp
  pugixml_vs2019_static.vcxproj -> C:\projects\pugixml\scripts\vs2019\x64_ReleaseStatic\pugixml.lib
vs2019/Win32_ReleaseStatic/pugixml.lib -> nuget/build/native/lib/Win32/v142/static/Release/pugixml.lib
vs2019/x64_ReleaseStatic/pugixml.lib -> nuget/build/native/lib/x64/v142/static/Release/pugixml.lib
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\projects\pugixml\scripts\pugixml_vs2017.vcxproj]`

**Comment by Joelgranados** [comment]
@zeux It may be the case that AppVeyor needs to install VS2017 and VS2015 in their VS2019 agent. Not sure at this point.

**Comment by zeux** [comment]
Ok. If you change the PR to keep the VS2017 image building the 2013/2015/2017 package, and VS2019 image building just 2019 package then I can merge it and then separately look into either merging the (two) resulting packages manually or fixing up AppVeyor setup to build everything on VS2019 image instead.

**Comment by Joelgranados** [comment]
@zeux : changed the PR so it will build in 3 agents (201{5,7,9}). It did not like when I removed the 15.
The 2019 agent creates a nuget that will only have v142.
The 2017 agent will create a nuget that will have v141, v140, v120
The 2015 agent will create a nuget that will have v140, v120

**Comment by zeux** [comment]
Thanks! According to Appveyor documentation, VS2017 et al aren't available in VS2019 image but it looks like merging two native NuGet packages is reasonably straightforward.

**Comment by Joelgranados** [comment]
@zeux : When do you think it will make it into nuget.org?

**Pull request merged**
