### PR TITLE
clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Removed problematic commits and added another one.

**Comment by neheb** [comment]
Added extra fixes.

**Comment by neheb** [comment]
Removed problematic stuff. Travis seems totally broken.

**Comment by zeux** [comment]
Closing this:

- NULL changes tracked here #586 (only interested in fixing gcc compilation warning, not clang-tidy)
- I will not merge C++ header changes because that results in needless compatibility complications for very old toolchains that I would still like to support
- Other stylistic fixes (like namespace comments and variable renames) should be fine but they will need to be submitted separately.

**Pull request closed without merging**
