### PR TITLE
Fixing possible null pointer dereference

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by zeux** [comment]
Is there any more detail on how this happened? Is this a real null pointer dereference, or is it reported by a static analysis tool (if so, which one?). Asking because as far as I can tell it should not be possible to get into this situation although the function logic is a bit messy and probably needs cleanup.

**Comment by valeriyvan** [comment]
Static analyser of Xcode. And it seems like exclusion path where null dereference might happen really exists.

**Comment by zeux** [comment]
The static analyzer seems to think that .root() of a non-null node can return a null node, but this is false.

**Comment by valeriyvan** [comment]
It's the latest Xcode, which is Version 11.2.1.
Please have a look into diagnostic.
Sure, all static analysers might be false positive.
But it shows very deep execution path where nil might appear.
Probably there's a bug on some levels up.

**Comment by zeux** [comment]
After looking at the code more I'm 99% confident this is not a real bug. Static analyzers sometimes may find issues but my general experience is summarized here: https://github.com/zeux/pugixml/issues/299#issuecomment-535100653. Regardless, as I said, it would be nice to keep the code clean of static analysis issues - I can reproduce this on clang9 and I'll take a look at the other two issues.

**Pull request merged**
