### PR TITLE
Add noexcept specifiers to move special members where possible

### PR DESCRIPTION
**Pull request by brandl-muc**
Having move special members is only half the deal. If they are not noexcept then for example std::vector::push_back will copy instead of move to keep giving the strong exception guarantee.
Therefore this PR adds noexcept to those special move members that can be made noexcept.

Also see these coding guidelines:
- [Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-move-noexcept)
- [High Integrity C++ Coding Standard](http://www.codingstandard.com/rule/12-5-4-declare-noexcept-the-move-constructor-and-move-assignment-operator/)

### CODE REVIEW

**Comment by zeux** [comment]
Yeah I considered something like this before. I'm not sure about marking the delete paths as noexcept - I believe starting in C++17 noexcept is part of the function type. This - as far as I understand - means that deallocation callback will have to be marked as noexcept, which will be a breaking change.

**Comment by brandl-muc** [comment]
noexcept cannot be part of typedefs so you cannot mark it as noexcept. However it would still be a bad idea to use something that throws as it is used in destructors which are implicitly noexcept. (and generally should not throw)

**Comment by zeux** [comment]
Right - I'm not worried about memory deallocation functions throwing. I'm worried about C++17 making the compiler aware of the distinction between noexcept function pointer and non-noexcept function pointer, and generating a warning/error when used to deallocate memory.

**Comment by brandl-muc** [comment]
Where is the problem if you leave the deallocation function pointer  `noexcept(false)` as it is already? It is perfectly legal to call a `noexcept(false)` function from a `noexcept(true)` one.
Then both types of functions can bind to the pointer. I don't expect compilers to warn in the above case because there would be a lot of false positives. E.g., on [coliru](http://coliru.stacked-crooked.com/a/437d3711a502c0f2) no warning is issued.

**Comment by zeux** [comment]
> It is perfectly legal to call a noexcept(false) function from a noexcept(true) one.

I expected this to not be the case, based on your changes to `delete_xpath_variable` but I've never used `noexcept` before so I could be wrong. I'll need to look into this a bit.

**Comment by brandl-muc** [comment]
Ah ok sure, I understand.
I googled a bit and found this SO question: [Can a noexcept function still call a function that throws in C++17?](https://stackoverflow.com/q/39763401/1969455)

Also we could discuss to what extent you would want to propagate `noexcept`. I only added it to the move special members and the functions they are calling. I assumed the deallocation function pointer to be "conceptually `noexcept`" and therefore stopped with functions that are calling `xml_memory::deallocate()`. It is also possible to check all functions and add `noexcept` if possible, or only add it to dtors to make them explicitly `noexcept`.

As a side node, obviously it would be nice to have `noexcept` move special members for `xml_document` which does not seem feasible with the current implementation. Is opening an issue to discuss this a good idea?

**Comment by zeux** [comment]
> As a side node, obviously it would be nice to have noexcept move special members for xml_document which does not seem feasible with the current implementation. Is opening an issue to discuss this a good idea?

The current implementation can be noexcept unless PUGIXML_COMPACT is defined; if it is, in some cases moving has to allocate which could throw. This is currently unavoidable; fixing that requires some changes in compact encoding that I was somewhat reluctant to make for the sake of move.

From what I can see, gcc doesn't actually check control flow for noexcept function to issue warnings which is somewhat odd (except for Wnoexcept which does something else); https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61372 was filed a while ago with no apparent action. One possibility is to either leave the change as is, or keep the noexcept annotations on just move machinery (ctor, operator=, _move). If warnings come up in the future we can deal with them then I guess.

**Comment by brandl-muc** [comment]
OK, I'll reduce the `noexcept`s in this PR.

I'm thinking of creating a second PR which contains the deallocation in a `try catch(...)` block. Throwing and catching is allowed in noexcept functions, but the exception [must not leave the function](https://stackoverflow.com/a/28975292/1969455).

I 'm also considering to create a third one with conditional `noexcept` for xml_document. What do you think?

**Comment by brandl-muc** [comment]
OK, I'll reduce the `noexcept`s in this PR.

I'm thinking of creating a second PR which contains the deallocation in a `try catch(...)` block. Throwing and catching is allowed in noexcept functions, but the exception [must not leave the function](https://stackoverflow.com/a/28975292/1969455).

I 'm also considering to create a third one with conditional `noexcept` for xml_document. What do you think?

**Comment by zeux** [comment]
Thanks! Merged - I think this is a good step. I don't think try/catch is a good idea - if the deallocation function does throw, I'm not sure what the exception handler would do. If an exception leaves the function, I'd expect std::terminate to get called which is reasonable - it's a fatal error.

noexcept for xml_document move functions would make sense. Since it's not available in some configurations it might make sense to create a special macro for this to keep the usage cleaner, like PUGIXML_NOEXCEPT_DOCMOVE or something.

**Pull request merged**
