### PR TITLE
Put CMakeLists.txt in the project root.

### PR DESCRIPTION
**Pull request by jippeholwerda**
Having CMakeLists.txt in the project root makes it so much easier to use pugixml
as an external dependency in another CMake project.

### CODE REVIEW

**Comment by snikulov** [comment]
@zeux  :+1: I also vote for this change. 
It'll help to re-use your project easily with External_ProjectAdd.

**Comment by zeux** [comment]
There's a small issue with putting CMakeLists.txt in the root - running cmake will probably overwrite the default Makefile. Also I guess some Linux distributions will have to adjust their packaging scripts as a result of this change (although I could temporarily leave CMakeLists.txt in scripts/ folder, and remove it in a following version).

Regardless, this seems like a good change. I'll test this a bit before merging.

**Comment by snikulov** [comment]
@zeux you can enforce out-of-source build, as clang do and as I've implemented for splunk/pion to avoid default makefile overwrite.

**Comment by snikulov** [comment]
Here the [example](https://github.com/splunk/pion/blob/develop/cmake/PionUtils.cmake#L50)

**Comment by rolftimmermans** [comment]
Any news on this? Thanks!

**Pull request merged**
