### PR TITLE
Feature single quote support

### PR DESCRIPTION
**Pull request by m-naumann**
closes https://github.com/zeux/pugixml/issues/274

### CODE REVIEW

**Comment by zeux** [comment]
I believe this is missing a change to node_output for escaping - will need to add escaping using & apos; and extend ctc_special_attr mask to include single quote.

**Comment by m-naumann** [comment]
I think you are talking about these lines: https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L2530 and https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L2570
where you replace `&apos;` by `'` and `&quot;` by `"`, right?

Can you explain again what to change there (and maybe why, for my understanding)? 
(The characters quote and apostrophe are still the same, right? We don't want to exchange them, do we?)

And I couldn't find `ctc_special_attr` in the source code, can you provide a line for that? (Again for my understanding: You were supporting reading single quotes already, it's just about writing them now, right?)

**Comment by zeux** [comment]
> Can you explain again what to change there (and maybe why, for my understanding)?
> (The characters quote and apostrophe are still the same, right? We don't want to exchange them, do we?)

My point is that before your change, with double quotes used as an attribute character, this:

```
node.append_attribute("name").set_value("val\"ue");
```

would result in this XML output:

```
<node name="val&quot;ue" />
```

After your change, setting the flag to use single quotes and using this code:

```
node.append_attribute("name").set_value("val'ue");
```

would result in this XML output:

```
<node name='val'ue' />
```

which is malformed; the correct output is `'val&apos;ue'`.

> And I couldn't find ctc_special_attr in the source code, can you provide a line for that?

Sorry, I meant `ctx_special_attr`. `chartypeex_table` needs to be extended to mark single quote as "special" character in attributes, and `text_output_escaped` needs to be extended to escape single quote as well, not just double quote.

**Comment by m-naumann** [comment]
Okay, got it, should be fixed by https://github.com/zeux/pugixml/pull/275/commits/bcfdfd59b1ac9f8571b12bc88cded903d15158c3

**Comment by zeux** [comment]
Thanks!

**Pull request merged**
